- id: uwotm8
  name: uwotm8 (American to British English)
  description: Converts American English spelling to British English spelling in text files
  entry: uwotm8
  args:
    - --comments-only
  language: python
  pass_filenames: true
  files: "(.*\.py|.*\.md|.*\.txt)"
